FROM node:14-alpine

WORKDIR /usr/src/app

COPY package.json .
RUN npm install --only=production
COPY . .

# Set a non-root user to improve security
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 3000

CMD ["node", "index.js"]