name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main 

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: List files for troubleshooting
      #   run: ls -R
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: DockerFileFolder/
          file: DockerFileFolder/DockerFile
          push: true
          tags: |
            yrnp2355/testrepo:${{ github.sha }}  # Use commit SHA as the tag
            yrnp2355/testrepo:latest              # Optional: latest tag